"""remove_foreignkey_userid

Revision ID: 433347ddc717
Revises: 6ed339fe8a9c
Create Date: 2023-11-11 02:01:11.995184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433347ddc717'
down_revision = '6ed339fe8a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=140), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('filepath', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_post_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
