"""newpostid_added

Revision ID: 2b7cf4be2e5a
Revises: c75541b01c08
Create Date: 2023-11-20 11:25:06.886675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7cf4be2e5a'
down_revision = 'c75541b01c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postid', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('postid', ['postid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('postid', type_='unique')
        batch_op.drop_column('postid')

    # ### end Alembic commands ###
