"""newtagid_added

Revision ID: a4be6725fb42
Revises: 0c09c032ad54
Create Date: 2023-11-20 14:31:00.857332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4be6725fb42'
down_revision = '0c09c032ad54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagid', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint('tagid', ['tagid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint('tagid', type_='unique')
        batch_op.drop_column('tagid')

    # ### end Alembic commands ###
