"""fs_unique

Revision ID: dfb81fc9eb28
Revises: 37e70c843686
Create Date: 2023-12-06 20:46:49.775835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb81fc9eb28'
down_revision = '37e70c843686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint("fs_uniquifier", ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("fs_uniquifier", type_='unique')
        batch_op.drop_column('fs_uniquifier')

    # ### end Alembic commands ###
